server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
producer:
  rabbitmq:
    exchange: example-exchange
    routingkey: example-routingkey
